### ISSUE TITLE
& in <title> gets wrapped in <span class="amp"></span>

### ISSUE THREAD

**Issue by Anteru** [mintchaos/typogrify#48]
The title says it all - typogrify mangles a title element like `<title>A & B</title>` into `<title>A <span class="amp">&</span> B</title>`, which unfortunately ends up being shown as "A <span class="amp">&</span>" by the browser.

**Comment by justinmayer** [comment]
The most expedient way to solve this is to filter at the template level, e.g., using the Jinja2 `striptags` filter.
