### ISSUE TITLE
Markdown documents in `STATIC_PATHS` are being parsed as articles

### ISSUE THREAD

**Issue by Granitosaurus** [mintchaos/typogrify#58]
The documentation indicates:
```
# static paths will be copied without parsing their contents
STATIC_PATHS = [
    'images',
    'extra/robots.txt',
    ]
```

However if you create `content/images/foo.md` Pelican still tries to interpret it as an article:
```
ERROR: Skipping /home/user/blog/content/images/foo.md: could not find information about 'title'
```
Which is very inconvenient if you want to add some non-article markdown files. For my particular case I use mdx_include markdown extension to embed some static intros/outros to blog posts as described in: https://docs.getpelican.com/en/latest/content.html?highlight=mdx_include#including-other-files

**Comment by justinmayer** [comment]
Why did you file this issue in the Typogrify repo?

**Comment by Granitosaurus** [comment]
oops I'm so sorry, wrong browser tab :D
