### ISSUE TITLE
New release on pypi

### ISSUE THREAD

**Issue by benkonrath** [mintchaos/typogrify#62]
Any chance we can get a new release on pypi?. There are some Python 3.12 warnings that have been fixed but haven't been published. Thanks.

**Comment by justinmayer** [comment]
Hi Ben. Would you do me a favor and please check existing issues, including closed ones, before filing new issues? Thanks — much appreciated.

**Comment by justinmayer** [comment]
I am packing for a trip, had only a moment to respond, and wanted to point out that a similar issue was just filed three days ago. No offense was intended.

I fully intend to issue a new release, which I will do upon my return from the aforementioned trip.

**Comment by justinmayer** [comment]
Via a [maintained fork of this project](https://github.com/justinmayer/typogrify), I just released [Typogrify 2.1](https://github.com/justinmayer/typogrify/releases/tag/2.1.0).
